### ISSUE TITLE
Can't Use Rythm Bot With Webhook

### ISSUE THREAD

**Issue by JofuTV** [logicallysound/streamdeck-discord-message#14]
Hey! I read around the other replies, but couldn't figure out a work around. 

Is there any way to control a Music Bot with this plugin? I seen that "Post as Actual User" is closed, but I can't seem to figure out another way to make it work. I doubt Rythm Bot is going to change their Bot just for me lol 

But if there is a work around, has anyone figured it out?

**Comment by logicallysound** [comment]
If there were an easy workaround for this it would likely be a highly concerning security issue for Discord because it would mean that (potentially) bad actors could silently post to Discord (and possibly perform other actions) on your behalf.

Short of doing the full OAuth dance I don't see how it'd be possible to fix this for everyone but I'm happy to leave this open for a while in case others have ideas.

The main workarounds that others have used are getting the bot to change to listen to commands issued by other bot accounts or switching to a different music bot that doesn't ignore other bots.

**Comment by JofuTV** [comment]
Thanks for replying! 
I have not found any music bots that listen to other bots 
The workout around I did was - use Auto HotKey to type as me the !play command. And I have different playlist on the stream deck. It requires me to be in the channel I’m music spamming. It worked for my long Tabletop session, but I want a more permanent solution. If someone knows of a bit that listens to bots - I’d gladly check it out. 

Thanks again for the help!

**Comment by logicallysound** [comment]
I think one is mentioned in the comments of an older issue related to this but I might be mistaken?

**Comment by logicallysound** [comment]
Closing as a dupe of #7 though I still recommend working around the issue by using a bot that will respond to another bot's messages rather than waiting on a fix for the issue since it's an incredibly difficult issue for me to solve at the moment.
